#!/usr/bin/env python3
"""Regenerate the dtype fact tables that rnp-core's unit tests assert against.

Everything written here is probed from the real numpy 2.5.2 in `.venv`; no
entry is written by hand. Run:

    .venv/bin/python harness/gen_tables.py
"""
import itertools
import operator
import warnings
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "rnp" / "crates" / "rnp-core" / "src"

# numpy name -> rnp-core `DType` variant.
DTYPES = {
    "bool": "Bool",
    "int8": "I8",
    "int16": "I16",
    "int32": "I32",
    "int64": "I64",
    "uint8": "U8",
    "uint16": "U16",
    "uint32": "U32",
    "uint64": "U64",
    "float16": "F16",
    "float32": "F32",
    "float64": "F64",
    "complex64": "C64",
    "complex128": "C128",
}


def gen_promotion() -> str:
    lines = [
        "// Generated from real numpy 2.5.2 via numpy.promote_types. "
        "Do not edit by hand.",
        "[",
    ]
    for a, b in itertools.product(DTYPES, DTYPES):
        r = str(np.promote_types(a, b))
        lines.append(f"    (DType::{DTYPES[a]}, DType::{DTYPES[b]}, DType::{DTYPES[r]}),")
    lines.append("]")
    return "\n".join(lines) + "\n"


def gen_casting() -> str:
    """(from, to, safe, same_kind) for every numeric pair."""
    lines = [
        "// Generated from real numpy 2.5.2 via numpy.can_cast. "
        "Do not edit by hand.",
        "// (from, to, safe, same_kind)",
        "[",
    ]
    for a, b in itertools.product(DTYPES, DTYPES):
        safe = str(bool(np.can_cast(a, b, "safe"))).lower()
        same = str(bool(np.can_cast(a, b, "same_kind"))).lower()
        lines.append(f"    (DType::{DTYPES[a]}, DType::{DTYPES[b]}, {safe}, {same}),")
    lines.append("]")
    return "\n".join(lines) + "\n"


def gen_string_lengths() -> str:
    """Smallest `S<n>`/`U<n>` each numeric dtype casts safely into."""
    lines = [
        "// Generated from real numpy 2.5.2: the smallest n for which "
        "can_cast(dtype, 'S<n>') holds.",
        "// Do not edit by hand.",
        "[",
    ]
    for name, variant in DTYPES.items():
        n = next(n for n in range(1, 512) if np.can_cast(name, f"S{n}"))
        m = next(n for n in range(1, 512) if np.can_cast(name, f"U{n}"))
        assert n == m, (name, n, m)
        lines.append(f"    (DType::{variant}, {n}),")
    lines.append("]")
    return "\n".join(lines) + "\n"


#: numpy's 13 real datetime units, coarse to fine, plus the generic unit.
DT_UNITS = ["Y", "M", "W", "D", "h", "m", "s", "ms", "us", "ns", "ps", "fs",
            "as"]

#: numpy's `NPY_DATETIMEUNIT` values. The gap at 3 is the removed business-day
#: unit, whose enum slot was kept so the ordering never changed.
DT_BASE = {"Y": 0, "M": 1, "W": 2, "D": 4, "h": 5, "m": 6, "s": 7, "ms": 8,
           "us": 9, "ns": 10, "ps": 11, "fs": 12, "as": 13, "generic": 14}


def _dt_result(expr):
    """Evaluate a probe, returning `("ok", base, num)` or `("err", cls)`."""
    try:
        d = expr()
    except Exception as e:  # noqa: BLE001
        return ("err", type(e).__name__)
    unit, num = np.datetime_data(d)
    return ("ok", DT_BASE[unit], num)


def gen_datetime_units() -> str:
    """The datetime/timedelta unit tables rnp-core's tests assert against.

    Two tables, both probed from real numpy 2.5.2, over all 14x14 ordered
    pairs of the 13 real units plus the generic one:

    * the timedelta table -- `np.promote_types('m8[A]', 'm8[B]')`, which is
      the *strict* metadata GCD (years/months are incommensurate with
      everything finer);
    * the datetime table  -- the same for `M8`, which is the *relaxed* GCD
      (`M8[Y]` and `M8[D]` do have a common unit).

    A pair numpy rejects is recorded as `None`.
    """
    units = DT_UNITS + ["generic"]

    def spell(kind, u):
        return f"{kind}8" if u == "generic" else f"{kind}8[{u}]"

    lines = [
        "// Generated by harness/gen_tables.py from real numpy 2.5.2.",
        "// Do not edit by hand.",
        "//",
        "// (a_base, b_base, result) where `result` is Some((base, num))",
        "// or None when numpy raises.",
        "(",
        "// --- np.promote_types on two timedelta64 dtypes (strict GCD) ---",
        "&[",
    ]
    for a, b in itertools.product(units, units):
        r = _dt_result(lambda: np.promote_types(spell("m", a), spell("m", b)))
        cell = "None" if r[0] == "err" else f"Some(({r[1]}, {r[2]}))"
        lines.append(f"    ({DT_BASE[a]}, {DT_BASE[b]}, {cell}),")
    lines += ["],",
              "// --- np.promote_types on two datetime64 dtypes (relaxed GCD) ---",
              "&["]
    for a, b in itertools.product(units, units):
        r = _dt_result(lambda: np.promote_types(spell("M", a), spell("M", b)))
        cell = "None" if r[0] == "err" else f"Some(({r[1]}, {r[2]}))"
        lines.append(f"    ({DT_BASE[a]}, {DT_BASE[b]}, {cell}),")
    lines += ["],", ")"]
    return "\n".join(lines) + "\n"


def gen_datetime_ops() -> str:
    """Result unit of the datetime arithmetic ufuncs, per ordered unit pair."""
    units = DT_UNITS + ["generic"]

    def arr(kind, u, v=1):
        spec = f"{kind}8" if u == "generic" else f"{kind}8[{u}]"
        return np.array([v], spec)

    lines = [
        "// Generated by harness/gen_tables.py from real numpy 2.5.2.",
        "// Do not edit by hand.",
        "//",
        "// (op, a_kind, a_base, b_kind, b_base, result) with kinds 'M'/'m',",
        "// result = Some((kind, base, num)) or None when numpy raises.",
        "&[",
    ]
    ops = [("+", operator.add), ("-", operator.sub), ("/", operator.truediv)]
    kinds = ["M", "m"]
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        for opname, fn in ops:
            for ka, kb in itertools.product(kinds, kinds):
                for a, b in itertools.product(units, units):
                    try:
                        r = fn(arr(ka, a), arr(kb, b))
                    except Exception:  # noqa: BLE001
                        cell = "None"
                    else:
                        if r.dtype.kind in "Mm":
                            u, n = np.datetime_data(r.dtype)
                            cell = (f"Some(('{r.dtype.kind}', "
                                    f"{DT_BASE[u]}, {n}))")
                        else:
                            cell = f"Some(('{r.dtype.char}', 0, 0))"
                    lines.append(
                        f"    ('{opname}', '{ka}', {DT_BASE[a]}, "
                        f"'{kb}', {DT_BASE[b]}, {cell}),")
    lines.append("]")
    return "\n".join(lines) + "\n"


def main() -> None:
    (SRC / "promotion_table.inc").write_text(gen_promotion())
    (SRC / "casting_table.inc").write_text(gen_casting())
    (SRC / "string_lengths.inc").write_text(gen_string_lengths())
    (SRC / "datetime_units.inc").write_text(gen_datetime_units())
    (SRC / "datetime_ops.inc").write_text(gen_datetime_ops())
    print(f"wrote promotion/casting/string-length/datetime tables to {SRC}")


if __name__ == "__main__":
    main()
