"""Generated from real numpy 2.5.2 by harness/gen_tables.py --ufuncs.

Maps each ufunc name to (nin, nout, identity, types). The `types`
strings are what `np.<f>.types` reports and what upstream tests read.
"""

from math import inf, nan  # noqa: F401

TABLE = {
    'abs': (1, 1, None, ['?->?', 'b->b', 'B->B', 'h->h', 'H->H', 'i->i', 'I->I', 'l->l', 'L->L', 'q->q', 'Q->Q', 'e->e', 'f->f', 'd->d', 'g->g', 'm->m', 'F->f', 'D->d', 'G->g', 'O->O']),
    'absolute': (1, 1, None, ['?->?', 'b->b', 'B->B', 'h->h', 'H->H', 'i->i', 'I->I', 'l->l', 'L->L', 'q->q', 'Q->Q', 'e->e', 'f->f', 'd->d', 'g->g', 'm->m', 'F->f', 'D->d', 'G->g', 'O->O']),
    'acos': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'acosh': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'add': (2, 1, 0, ['??->?', 'bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'Mm->M', 'mm->m', 'mM->M', 'OO->O']),
    'arccos': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'arccosh': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'arcsin': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'arcsinh': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'arctan': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'arctan2': (2, 1, None, ['ee->e', 'ff->f', 'dd->d', 'gg->g', 'OO->O']),
    'arctanh': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'asin': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'asinh': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'atan': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'atan2': (2, 1, None, ['ee->e', 'ff->f', 'dd->d', 'gg->g', 'OO->O']),
    'atanh': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'bitwise_and': (2, 1, -1, ['??->?', 'bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'OO->O']),
    'bitwise_count': (1, 1, None, ['b->B', 'B->B', 'h->B', 'H->B', 'i->B', 'I->B', 'l->B', 'L->B', 'q->B', 'Q->B', 'O->O']),
    'bitwise_invert': (1, 1, None, ['?->?', 'b->b', 'B->B', 'h->h', 'H->H', 'i->i', 'I->I', 'l->l', 'L->L', 'q->q', 'Q->Q', 'O->O']),
    'bitwise_left_shift': (2, 1, None, ['bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'OO->O']),
    'bitwise_not': (1, 1, None, ['?->?', 'b->b', 'B->B', 'h->h', 'H->H', 'i->i', 'I->I', 'l->l', 'L->L', 'q->q', 'Q->Q', 'O->O']),
    'bitwise_or': (2, 1, 0, ['??->?', 'bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'OO->O']),
    'bitwise_right_shift': (2, 1, None, ['bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'OO->O']),
    'bitwise_xor': (2, 1, 0, ['??->?', 'bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'OO->O']),
    'cbrt': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'O->O']),
    'ceil': (1, 1, None, ['?->?', 'b->b', 'B->B', 'h->h', 'H->H', 'i->i', 'I->I', 'l->l', 'L->L', 'q->q', 'Q->Q', 'e->e', 'f->f', 'd->d', 'f->f', 'd->d', 'g->g', 'O->O']),
    'conj': (1, 1, None, ['b->b', 'B->B', 'h->h', 'H->H', 'i->i', 'I->I', 'l->l', 'L->L', 'q->q', 'Q->Q', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'conjugate': (1, 1, None, ['b->b', 'B->B', 'h->h', 'H->H', 'i->i', 'I->I', 'l->l', 'L->L', 'q->q', 'Q->Q', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'copysign': (2, 1, None, ['ee->e', 'ff->f', 'dd->d', 'gg->g']),
    'cos': (1, 1, None, ['e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'cosh': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'deg2rad': (1, 1, None, ['e->e', 'f->f', 'd->d', 'g->g', 'O->O']),
    'degrees': (1, 1, None, ['e->e', 'f->f', 'd->d', 'g->g', 'O->O']),
    'divide': (2, 1, None, ['ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'mq->m', 'md->m', 'mm->d', 'OO->O']),
    'divmod': (2, 2, None, ['bb->bb', 'BB->BB', 'hh->hh', 'HH->HH', 'ii->ii', 'II->II', 'll->ll', 'LL->LL', 'qq->qq', 'QQ->QQ', 'ee->ee', 'ff->ff', 'dd->dd', 'gg->gg', 'mm->qm']),
    'equal': (2, 1, None, ['??->?', 'bb->?', 'BB->?', 'hh->?', 'HH->?', 'ii->?', 'II->?', 'll->?', 'LL->?', 'qq->?', 'QQ->?', 'qQ->?', 'Qq->?', 'ee->?', 'ff->?', 'dd->?', 'gg->?', 'FF->?', 'DD->?', 'GG->?', 'MM->?', 'mm->?', 'OO->?', 'OO->O']),
    'exp': (1, 1, None, ['e->e', 'f->f', 'd->d', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'exp2': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'expm1': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'fabs': (1, 1, None, ['e->e', 'f->f', 'd->d', 'g->g', 'O->O']),
    'float_power': (2, 1, None, ['dd->d', 'gg->g', 'DD->D', 'GG->G']),
    'floor': (1, 1, None, ['?->?', 'b->b', 'B->B', 'h->h', 'H->H', 'i->i', 'I->I', 'l->l', 'L->L', 'q->q', 'Q->Q', 'e->e', 'f->f', 'd->d', 'f->f', 'd->d', 'g->g', 'O->O']),
    'floor_divide': (2, 1, None, ['bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'mq->m', 'md->m', 'mm->q', 'OO->O']),
    'fmax': (2, 1, None, ['??->?', 'bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'mm->m', 'MM->M', 'OO->O']),
    'fmin': (2, 1, None, ['??->?', 'bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'mm->m', 'MM->M', 'OO->O']),
    'fmod': (2, 1, None, ['bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'OO->O']),
    'frexp': (1, 2, None, ['e->ei', 'f->fi', 'd->di', 'g->gi']),
    'gcd': (2, 1, 0, ['bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'OO->O']),
    'greater': (2, 1, None, ['??->?', 'bb->?', 'BB->?', 'hh->?', 'HH->?', 'ii->?', 'II->?', 'll->?', 'LL->?', 'qq->?', 'QQ->?', 'qQ->?', 'Qq->?', 'ee->?', 'ff->?', 'dd->?', 'gg->?', 'FF->?', 'DD->?', 'GG->?', 'MM->?', 'mm->?', 'OO->?', 'OO->O']),
    'greater_equal': (2, 1, None, ['??->?', 'bb->?', 'BB->?', 'hh->?', 'HH->?', 'ii->?', 'II->?', 'll->?', 'LL->?', 'qq->?', 'QQ->?', 'qQ->?', 'Qq->?', 'ee->?', 'ff->?', 'dd->?', 'gg->?', 'FF->?', 'DD->?', 'GG->?', 'MM->?', 'mm->?', 'OO->?', 'OO->O']),
    'heaviside': (2, 1, None, ['ee->e', 'ff->f', 'dd->d', 'gg->g']),
    'hypot': (2, 1, 0, ['ee->e', 'ff->f', 'dd->d', 'gg->g', 'OO->O']),
    'invert': (1, 1, None, ['?->?', 'b->b', 'B->B', 'h->h', 'H->H', 'i->i', 'I->I', 'l->l', 'L->L', 'q->q', 'Q->Q', 'O->O']),
    'isfinite': (1, 1, None, ['?->?', 'b->?', 'B->?', 'h->?', 'H->?', 'i->?', 'I->?', 'l->?', 'L->?', 'q->?', 'Q->?', 'e->?', 'f->?', 'd->?', 'g->?', 'F->?', 'D->?', 'G->?', 'm->?', 'M->?']),
    'isinf': (1, 1, None, ['?->?', 'b->?', 'B->?', 'h->?', 'H->?', 'i->?', 'I->?', 'l->?', 'L->?', 'q->?', 'Q->?', 'e->?', 'f->?', 'd->?', 'g->?', 'F->?', 'D->?', 'G->?', 'm->?', 'M->?']),
    'isnan': (1, 1, None, ['?->?', 'b->?', 'B->?', 'h->?', 'H->?', 'i->?', 'I->?', 'l->?', 'L->?', 'q->?', 'Q->?', 'e->?', 'f->?', 'd->?', 'g->?', 'F->?', 'D->?', 'G->?', 'm->?', 'M->?']),
    'isnat': (1, 1, None, ['M->?', 'm->?']),
    'lcm': (2, 1, None, ['bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'OO->O']),
    'ldexp': (2, 1, None, ['ei->e', 'fi->f', 'el->e', 'fl->f', 'di->d', 'dl->d', 'gi->g', 'gl->g']),
    'left_shift': (2, 1, None, ['bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'OO->O']),
    'less': (2, 1, None, ['??->?', 'bb->?', 'BB->?', 'hh->?', 'HH->?', 'ii->?', 'II->?', 'll->?', 'LL->?', 'qq->?', 'QQ->?', 'qQ->?', 'Qq->?', 'ee->?', 'ff->?', 'dd->?', 'gg->?', 'FF->?', 'DD->?', 'GG->?', 'MM->?', 'mm->?', 'OO->?', 'OO->O']),
    'less_equal': (2, 1, None, ['??->?', 'bb->?', 'BB->?', 'hh->?', 'HH->?', 'ii->?', 'II->?', 'll->?', 'LL->?', 'qq->?', 'QQ->?', 'qQ->?', 'Qq->?', 'ee->?', 'ff->?', 'dd->?', 'gg->?', 'FF->?', 'DD->?', 'GG->?', 'MM->?', 'mm->?', 'OO->?', 'OO->O']),
    'log': (1, 1, None, ['e->e', 'f->f', 'd->d', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'log10': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'log1p': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'log2': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'logaddexp': (2, 1, -inf, ['ee->e', 'ff->f', 'dd->d', 'gg->g']),
    'logaddexp2': (2, 1, -inf, ['ee->e', 'ff->f', 'dd->d', 'gg->g']),
    'logical_and': (2, 1, True, ['??->?', 'bb->?', 'BB->?', 'hh->?', 'HH->?', 'ii->?', 'II->?', 'll->?', 'LL->?', 'qq->?', 'QQ->?', 'ee->?', 'ff->?', 'dd->?', 'gg->?', 'FF->?', 'DD->?', 'GG->?', 'OO->O']),
    'logical_not': (1, 1, None, ['?->?', 'b->?', 'B->?', 'h->?', 'H->?', 'i->?', 'I->?', 'l->?', 'L->?', 'q->?', 'Q->?', 'e->?', 'f->?', 'd->?', 'g->?', 'F->?', 'D->?', 'G->?', 'O->O']),
    'logical_or': (2, 1, False, ['??->?', 'bb->?', 'BB->?', 'hh->?', 'HH->?', 'ii->?', 'II->?', 'll->?', 'LL->?', 'qq->?', 'QQ->?', 'ee->?', 'ff->?', 'dd->?', 'gg->?', 'FF->?', 'DD->?', 'GG->?', 'OO->O']),
    'logical_xor': (2, 1, False, ['??->?', 'bb->?', 'BB->?', 'hh->?', 'HH->?', 'ii->?', 'II->?', 'll->?', 'LL->?', 'qq->?', 'QQ->?', 'ee->?', 'ff->?', 'dd->?', 'gg->?', 'FF->?', 'DD->?', 'GG->?', 'OO->O']),
    'matmul': (2, 1, None, ['??->?', 'bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'OO->O']),
    'matvec': (2, 1, None, ['??->?', 'bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'OO->O']),
    'maximum': (2, 1, None, ['??->?', 'bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'mm->m', 'MM->M', 'OO->O']),
    'minimum': (2, 1, None, ['??->?', 'bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'mm->m', 'MM->M', 'OO->O']),
    'mod': (2, 1, None, ['bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'mm->m', 'OO->O']),
    'modf': (1, 2, None, ['e->ee', 'f->ff', 'd->dd', 'g->gg']),
    'multiply': (2, 1, 1, ['??->?', 'bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'mq->m', 'qm->m', 'md->m', 'dm->m', 'OO->O']),
    'negative': (1, 1, None, ['b->b', 'B->B', 'h->h', 'H->H', 'i->i', 'I->I', 'l->l', 'L->L', 'q->q', 'Q->Q', 'e->e', 'f->f', 'd->d', 'g->g', 'm->m', 'F->F', 'D->D', 'G->G', 'O->O']),
    'nextafter': (2, 1, None, ['ee->e', 'ff->f', 'dd->d', 'gg->g']),
    'not_equal': (2, 1, None, ['??->?', 'bb->?', 'BB->?', 'hh->?', 'HH->?', 'ii->?', 'II->?', 'll->?', 'LL->?', 'qq->?', 'QQ->?', 'qQ->?', 'Qq->?', 'ee->?', 'ff->?', 'dd->?', 'gg->?', 'FF->?', 'DD->?', 'GG->?', 'MM->?', 'mm->?', 'OO->?', 'OO->O']),
    'positive': (1, 1, None, ['b->b', 'B->B', 'h->h', 'H->H', 'i->i', 'I->I', 'l->l', 'L->L', 'q->q', 'Q->Q', 'e->e', 'f->f', 'd->d', 'g->g', 'm->m', 'F->F', 'D->D', 'G->G', 'O->O']),
    'pow': (2, 1, None, ['bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'OO->O']),
    'power': (2, 1, None, ['bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'OO->O']),
    'rad2deg': (1, 1, None, ['e->e', 'f->f', 'd->d', 'g->g', 'O->O']),
    'radians': (1, 1, None, ['e->e', 'f->f', 'd->d', 'g->g', 'O->O']),
    'reciprocal': (1, 1, None, ['b->b', 'B->B', 'h->h', 'H->H', 'i->i', 'I->I', 'l->l', 'L->L', 'q->q', 'Q->Q', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'remainder': (2, 1, None, ['bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'mm->m', 'OO->O']),
    'right_shift': (2, 1, None, ['bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'OO->O']),
    'rint': (1, 1, None, ['e->e', 'f->f', 'd->d', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'sign': (1, 1, None, ['b->b', 'B->B', 'h->h', 'H->H', 'i->i', 'I->I', 'l->l', 'L->L', 'q->q', 'Q->Q', 'e->e', 'f->f', 'd->d', 'g->g', 'm->d', 'F->F', 'D->D', 'G->G', 'O->O']),
    'signbit': (1, 1, None, ['e->?', 'f->?', 'd->?', 'g->?']),
    'sin': (1, 1, None, ['e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'sinh': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'spacing': (1, 1, None, ['e->e', 'f->f', 'd->d', 'g->g']),
    'sqrt': (1, 1, None, ['e->e', 'f->f', 'd->d', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'square': (1, 1, None, ['b->b', 'B->B', 'h->h', 'H->H', 'i->i', 'I->I', 'l->l', 'L->L', 'q->q', 'Q->Q', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'subtract': (2, 1, None, ['bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'Mm->M', 'mm->m', 'MM->m', 'OO->O']),
    'tan': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'tanh': (1, 1, None, ['e->e', 'f->f', 'd->d', 'e->e', 'f->f', 'd->d', 'g->g', 'F->F', 'D->D', 'G->G', 'O->O']),
    'true_divide': (2, 1, None, ['ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'mq->m', 'md->m', 'mm->d', 'OO->O']),
    'trunc': (1, 1, None, ['?->?', 'b->b', 'B->B', 'h->h', 'H->H', 'i->i', 'I->I', 'l->l', 'L->L', 'q->q', 'Q->Q', 'e->e', 'f->f', 'd->d', 'f->f', 'd->d', 'g->g', 'O->O']),
    'vecdot': (2, 1, None, ['??->?', 'bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'OO->O']),
    'vecmat': (2, 1, None, ['??->?', 'bb->b', 'BB->B', 'hh->h', 'HH->H', 'ii->i', 'II->I', 'll->l', 'LL->L', 'qq->q', 'QQ->Q', 'ee->e', 'ff->f', 'dd->d', 'gg->g', 'FF->F', 'DD->D', 'GG->G', 'OO->O']),
}
