import numpy as np
o=lambda *xs: np.array(list(xs),dtype=object)
class T:
    def __init__(s,v):s.v=v
    def __repr__(s):return f"T({s.v})"
    def __add__(s,x): print(f"   {s!r}.__add__({x!r})"); return T(s.v+ (x.v if isinstance(x,T) else x))
    def __radd__(s,x): print(f"   {s!r}.__radd__({x!r})"); return T(s.v+(x.v if isinstance(x,T) else x))
print("sum order:"); print(repr(np.add.reduce(o(T(1),T(2),T(3),T(4),T(5)))))
print("empty sum:", repr(np.sum(o())), type(np.sum(o())))
print("empty prod:", repr(np.prod(o())), type(np.prod(o())))
print("empty add.reduce:", repr(np.add.reduce(o())))
for f in ("minimum","maximum","logical_and","logical_or","logical_xor","bitwise_and","bitwise_or","subtract"):
    try: print("empty",f, repr(getattr(np,f).reduce(o())))
    except Exception as e: print("empty",f, type(e).__name__+":",e)
print("sum ints:", repr(np.sum(o(1,2,3))), type(np.sum(o(1,2,3))))
print("prod:", repr(np.prod(o(2,3,4))))
print("min:", repr(np.min(o(3,1,2))), "max:", repr(np.max(o(3,1,2))))
print("any:", repr(np.any(o(0,0))), type(np.any(o(0,0))), " all:",repr(np.all(o(1,2))))
print("any dtype:", np.any(o(0,1)).__class__)
print("logical_or.reduce:", repr(np.logical_or.reduce(o(0,"",5))))
print("logical_and.reduce:", repr(np.logical_and.reduce(o(1,"a",5))))
print("accumulate:", repr(np.add.accumulate(o(1,2,3))), np.add.accumulate(o(1,2,3)).dtype)
print("multiply.accumulate:", repr(np.multiply.accumulate(o(1,2,3,4))))
print("reduceat:", repr(np.add.reduceat(o(1,2,3,4,5),[0,2])))
print("2d sum axis0:", repr(np.add.reduce(np.array([[1,2],[3,4]],dtype=object),axis=0)))
print("2d sum None:", repr(np.add.reduce(np.array([[1,2],[3,4]],dtype=object),axis=None)))
print("initial:", repr(np.add.reduce(o(1,2,3),initial=10)))
print("where:", repr(np.add.reduce(o(1,2,3),where=[True,False,True])))
print("cmp reduce:", repr(np.equal.reduce(o(1,1))))
print("out=:", end=" ")
out=np.empty(3,dtype=object); np.add(o(1,2,3),o(1,1,1),out=out); print(repr(out))
out2=np.empty(3,dtype=object); np.add(o(1,2,3),o(10,10,10),out=out2,where=[True,False,True]); print("where out:",repr(out2))
print("bcast:", repr(np.add(o(1,2,3), np.array([[10],[20]],dtype=object))))
print("0d:", repr(np.add(np.array(1,dtype=object), 2)), type(np.add(np.array(1,dtype=object),2)))
